# Generated by Django 2.2.10 on 2020-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name='Authentication',
        ),
    ]
